### ISSUE TITLE
error getting embeddings for: {insert file name}.md --> getting this error for every note

### ISSUE THREAD

**Issue by lunalsmojo** [brianpetro/obsidian-smart-connections#321]
Whenever I open a note it begins "Making Smart Connections," but fails with the message in the title of this issue. 

Interestingly, it seems like this is happening at the same point, when the counter is somewhere between 1400-1450 (it's moving too fast for me to see exactly what it is). This kinda makes me think the problem is something local, although I've seen other issues here with the same problem, but closed with no real solution. Does it begin searching for connections at a standard point? (such as top down of my vault or something)

I've gone through the standard troubleshooting stuff: exited and reopened obsidian, disabled and re-enabled plugin, even deleted and reinstalled plugin.
Test API key gives an error that it's not working properly. I don't know why this is; I even tried generating a new API key and it said the same.

The embeds are partially successful. I've used the "retry failed files" button several times, and embeddings-3.json has been getting bigger and bigger, ever so slowly (failed-embeddings.txt went from 741 -> 737 lines. It's remained 737 the last time I've used the retry failed button)

When I open the console log (I'm on Linux, so I use ctrl + shift + i) it says error 429 and references lines 1003, 1009, 1059, 1063, 1064 of the main.js file. 1003 and 1009 look like the commands to report error, 1059 is retries, and I can't figure out 1063,64. It also produces:
Error: Request failed, status 429
    at new t (app.js:1:1741363)
    at d_ (app.js:1:1741555)
    at app.js:1:1742232
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
I don't know what this means. When I click on the links it opens some super long JavaScript command. Js is lost on me, though, so I'm not sure what it means. Adding a screenshot too.

Oh, yeah... P.S. I'm on Ubuntu 23.04
![Snapshot_2023-08-28_01-36-17](https://github.com/brianpetro/obsidian-smart-connections/assets/37223965/97e59208-2a13-4909-ba1f-191fb65a789c)

**Comment by lunalsmojo** [comment]
@brianpetro bump for attention

**Comment by lunalsmojo** [comment]
Hi @brianpetro 

Yep, it was the payment info. It didn't dawn on me that the ChatGPT Plus =/= text-embedding-ada-002 :-{}
A cool 4.5cents later, I'm up and running :-D

I've been scouring for a way to leverage AI this way, but kept running my head into walls trying to figure out how to unify one of the many chatbot models with one of the many embedding models. I guess what I'm trying to say is, I'm really excited to get started working with this plugin. Thank for your work!

One more thing though... My ideal scenario would have the embedding and chat hosted locally (cutting out OpenAI... Privacy and such, ya know?). Could I pull this off by changing the `usedParams` and `reqParams` values for embeddings, and `smart_chat_model` for chat to reflect a local instance? A little plug and play, if you will... Or is thinking it would be that simple just wishful thinking? (Like I mentioned, Js is {mostly} lost on me)

**Comment by brianpetro** [comment]
😊

Glad to hear you got it working.

Which local models would you replace with? I've been keeping an eye on them, and do plan on making the option available when I see the right combination of performance and ease-of-use/installation.

The "plug and play" requirements are probably a little more nuanced than that, but only because the current version wasn't designed for model flexibility. However, future versions will be. 

🌴
