### ISSUE TITLE
Copy of Prompt Doesn't Work

### ISSUE THREAD

**Issue by dvansoye** [brianpetro/obsidian-smart-connections#945]
Hi,
I think I found a bug.

If I click on the copy icon for the prompt (that I enter), nothing gets put on the clipboard (See #1).

Here's what I found in the Console:

plugin:smart-connections:17913 Failed to copy message:  TypeError: Error processing argument at index 0, conversion failure from 
    at Clipboard.<anonymous> (app.js:1:2982923)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at g (app.js:1:235994)
    at r.writeText (app.js:1:2982829)
    at HTMLSpanElement.eval (plugin:smart-connections:17910:27)

If I click on the copy icon of the response (that SC responds with), it does work. (See #2). 

Also, is there a way to see what is being submitted to the model? It would be great to be able to click on the links (See #3). Maybe there's a workaround until then? Being able to click on the links is important if you are looking for a specific reference in a book or research paper. I can't create a footnote if I don't know the specific reference. I assume that others would find this useful.

![Screenshot 2024-12-29 125004](https://github.com/user-attachments/assets/de950914-9c77-4137-aed6-7c6651851747)

**Comment by brianpetro** [comment]
Hi @dvansoye and thanks for letting me know about the copy bug.

Regarding clicking into the lookup context, this was discussed at the last Community Lean Coffee meeting and improving the UI/UX of that component is on the roadmap 🌴

**Comment by brianpetro** [comment]
The copy bug still needs to be fixed, but I just shipped the expanding context items UI in the early-release (`v.2.4.14`). Screenshot below (click item to expand)

![image](https://github.com/user-attachments/assets/dda643cf-e36f-4efb-bafd-e1c87cb87d1d)

🌴
